package anagraficaCentrale.client.gui;

import java.awt.Color;

public class GUIConstants {
	
	public static final Color BACKGROUND_COLOR_1 = Color.decode("#f7f7f7");
	public static final Color COMUNE_COLOR = Color.decode("#8CD0E5");
	public static final Color OSPEDALE_COLOR = Color.decode("#826B88");
	public static final Color SCUOLA_COLOR = Color.decode("#DE786A");
	public static final Color OPERATION_PANEL_BACKGROUND = Color.WHITE;
	public static final Color RESOURCE_CARD_BACKGROUND = Color.WHITE;
	
	public static class LANG {
		public static final String lblCerca = "Cerca ";
		public static final String lblServizi = "Servizi";
		public static final String lblOperationPanelTitle = "Anagrafica Centrale";
		public static final String lblComuneTitle = "Anagrafe";
		public static final String lblOspedaleTitle = "Ospedale";
		public static final String lblScuolaTitle = "Scuola";
		public static final String lblAccountBtnSide = "Profilo";
		public static final String lblServiceBtnSide = "Servizi";
		public static final String lblNotificationBtnSide = "Notifiche";
		public static final String lblNotifiche = "Notifiche";
		public static final String lblLoginUsername = "Username";
		public static final String lblLoginPassword = "Password";
		public static final String lblLoadingMessage = "Caricamento in corso...";
		public static final String lblLoadingTitle = "  Anagrafica Centrale";
		public static final String popupClosureDesc = "Sicuro di voler uscire?";
		public static final String popupClosureTitle = "Esci dal programma";
		public static final String lblProfile = "Il mio Profilo";
		public static final String lblReportBtnSide = "Documenti";
		public static final String lblService = "Servizi";
		public static final String lblReport = "Report";
		public static final String lblCollapseBtnSide = "Chiudi";
		public static final String lblUserCreationSrvTitle = "Creazione Utente";
		public static final String lblCloseBtn = "Chiudi";
		public static final String userCreateConfirmMsg = "Per favore controlla i dati. Confermi di voler procedere alla creazione dell'utente?";
		public static final String userCreateConfirmTitle = "Creazione utente";
		public static final String lbluserCreationUsername = "Username";
		public static final String lbluserCreationFirstName = "Nome";
		public static final String lbluserCreationCreateUserBtn = "Salva";
		public static final String lbluserCreationTaxIDCode = "Codice Fiscale";
		public static final String lbluserCreationGender = "Sesso";
		public static final String lbluserCreationBirthDate = "Data di Nascita";
		public static final String lbluserCreationSurname = "Cognome";
		public static final String lbluserCreationAuthorization = "Autorizzazioni";
		public static final String lblErrorMandatoryField = "Campo obbligatorio";
		public static final String lblTaxIdWrongSize = "Formato errato";
		public static final String errFileCreationNameInvalid = "� necessario inserire il path completo del file";
		public static final String lblApplyFilterNoResults = "Nessun risultato";
		public static final String tooltipDeleteReadNotifBtn = "Cancella tutte le notifiche lette";
		public static final String lblExpandBtnSide = "Espandi/collassa menu";
		public static final String lblDeleteReadNotifBtn = "Cancella notifiche lette";
		public static final String msgUserCreateSuccess = "Utente creato con successo. Ricorda che la password iniziale � uguale allo user id!";
		public static final String lblAppointmentDate = "Data appuntamento";
		public static final String lblAppointmentCreateBtn = "Prenota";
		public static final String msgAppointmentSuccess = "Appuntamento richiesto con successo. Una volta confermata la data, riceverai una notifica.";
		public static final String lbl_APP_CI_SrvTitle = "Appuntamento Carta d'identit�";
		public static final String lblAppointmentListUser = "Intestatario richiesta";
		public static final String lbl_APP_CI_SrvText = "Gentile cittadino/a,\n\nPer richiedere il rilascio della carta d'identit� elettronica � necessario prenotare un appuntamento.\n\nDocumenti da presentare:\n� Documento di identit� valido (se disponibile)\n� Tessera sanitaria\n� Codice fiscale\n� Fototessera recente (formato 3x4 cm)\n\nDati anagrafici:";
		public static final String lbluserCreationBirthTown = "Citt� di nascita";
		public static final String lbluserCreationBirthState = "Stato di nascita";
		public static final String lbluserCreationAddress = "Indirizzo";
		public static final String lbluserCreationTown = "Citt� di residenza";
		public static final String lbluserCreationProvince = "Provincia";
		public static final String lbluserCreationState = "Stato";
		public static final String lbluserCreationZipCode = "CAP";
		public static final String lblErrorOnlyDigit = "Ammessi solo caratteri numerici";
		public static final String lblServiceCreateUser = "Crea utente";
		public static final String lblServiceAPP_CI = "Appuntamento Carta d'identit�";
		public static final String lblServiceCI_TEMP = "Carta d�identit� temporanea";
		public static final String lblServiceCAM_RES = "Cambio residenza";
		public static final String lblServiceCOLL_INS = "Richiesta colloquio insegnanti";
		public static final String lblServiceISCRIZ = "Domanda d'iscrizione";
		public static final String lblServicePAG_MEN = "Pagamento mensa";
		public static final String lblServicePAG_RET = "Pagamento retta";
		public static final String lblServicePAG_TICK = "Pagamento ticket";
		public static final String lblServicePREN_VIS = "Prenotazione visita";
		public static final String lblServiceCAM_MED = "Cambio medico";
		public static final String lblServiceSTAT_FAM = "Stato di famiglia";
		public static final String lblServiceCERT_MATR = "Certificato di matrimonio";
		public static final String lblServiceCERT_NASC = "Certificato di nascita";
		public static final String lbl_COLL_INS_SrvText = "TODO";
		public static final String lbl_COLL_INS_SrvTitle = "Colloquio insegnanti";
		public static final String lblErrorUnableToCreateConnection = "Impossibile stabilire una connessione con il server, riprovare?";
		public static final String msgSimpleRequestSuccess = "Richiesta sottomessa con successo";
		public static final String lblSimpleRequestCreateBtn = "Richiedi";
		public static final String lbl_CERT_NASC_SrvTitle = "Richiesta certificato di nascita";
		public static final String lbl_CERT_NASC_SrvText = "<html><body style=\"font-size: 16px;\"><p align=\"justify\" style=\"word-break:normal;white-space:normal\">Il/la sottoscritto/a <b>!first_name !surname</b>, nato/a a <b>!birth_town</b> (<b>!birth_province</b>) il <b>!birthdate</b>,<br/>CF <b>!tax_id_code</b> residente in via <b>!address, !town (!province), !zip_code</b></p><p align=\"center\"><b>RICHIEDE</b></p><p>l'emissione del certificato di Nascita</p></body></html>";
		public static final String lbl_CERT_MATR_SrvTitle = "Richiesta certificato di matrimonio";
		public static final String lbl_CERT_MATR_SrvText = "<html><body style=\"font-size: 16px;\"><p align=\"justify\" style=\"word-break:normal;white-space:normal\">Il/la sottoscritto/a <b>!first_name !surname</b>, nato/a a <b>!birth_town</b> (<b>!birth_province</b>) il <b>!birthdate</b>,<br/>CF <b>!tax_id_code</b> residente in via <b>!address, !town (!province), !zip_code</b></p><p align=\"center\"><b>RICHIEDE</b></p><p>l'emissione del certificato di Matrimonio</p></body></html>";
		public static final String lbl_STAT_FAM_SrvTitle = "Richiesta stato di famiglia";
		public static final String lbl_STAT_FAM_SrvText = "<html><body style=\"font-size: 16px;\"><p align=\"justify\" style=\"word-break:normal;white-space:normal\">Il/la sottoscritto/a <b>!first_name !surname</b>, nato/a a <b>!birth_town</b> (<b>!birth_province</b>) il <b>!birthdate</b>,<br/>CF <b>!tax_id_code</b> residente in via <b>!address, !town (!province), !zip_code</b></p><p align=\"center\"><b>RICHIEDE</b></p><p>l'emissione dello Stato di Famiglia</p></body></html>";
		public static final String lbl_CAM_RES_SrvTitle = "Richiesta di cambio residenza";
		public static final String lbl_CAM_RES_SrvText = "<html><body style=\"font-size: 16px;\"><p align=\"justify\" style=\"word-break:normal;white-space:normal\">Il/la sottoscritto/a <b>!first_name !surname</b>, nato/a a <b>!birth_town</b> (<b>!birth_province</b>) il <b>!birthdate</b>,<br/>CF <b>!tax_id_code</b> residente in via <b>!address, !town (!province), !zip_code</b></p><p align=\"center\"><b>RICHIEDE</b></p><p>che l'attuale indirizzo di residenza venga modificato con il seguente</p></body></html>";
		public static final String msgResidenceChangeSuccess = "Richiesta di cambio residenza inoltrata. Riceverai una notifica con il riscontro";
		public static final String lbluserCreationBirthProvince = "Provincia di nascita";
		public static final String msgCITempSuccess = "Carta d'identit� temporanea richiesta con successo";
		public static final String lblCI_TEMP_reason = "Motivo della richiesta";
		public static final String lbl_CI_TEMP_SrvTitle = "Carta d'identit� temporanea";
		public static final String lbl_CI_TEMP_SrvText = "<html><body style=\"font-size: 16px;\"><p align=\"justify\" style=\"word-break:normal;white-space:normal\">Il/la sottoscritto/a <b>!first_name !surname</b>, nato/a a <b>!birth_town</b> (<b>!birth_province</b>) il <b>!birthdate</b>,<br/>CF <b>!tax_id_code</b> residente in via <b>!address, !town (!province), !zip_code</b></p><p align=\"center\"><b>RICHIEDE</b></p><p>che venga rilasciato il documento temporaneo per i seguenti motivi</p></body></html>";
		public static final String lblPREN_VIS_visit = "Visita";
		public static final String lbl_PREN_VIS_SrvText = "Compila i seguenti dati per procedere alla prenotazione:";
		public static final String lbl_PREN_VIS_SrvTitle = "Prenotazione visita";
		public static final String msgCAM_MEDSuccess = "Richiesta di cambio medico inoltrata. Riceverai una notifica con il riscontro";
		public static final String lbl_CAM_MED_SrvTitle = "Richiesta cambio medico";
		public static final String lbl_CAM_MED_SrvText = "<html><body style=\"font-size: 16px;\"><p align=\"justify\" style=\"word-break:normal;white-space:normal\">Il/la sottoscritto/a <b>!first_name !surname</b>, nato/a a <b>!birth_town</b> (<b>!birth_province</b>) il <b>!birthdate</b>,<br/>CF <b>!tax_id_code</b> residente in via <b>!address, !town (!province), !zip_code</b></p><p align=\"center\"><b>RICHIEDE</b></p><p>che l'attuale medico venga modificato con il seguente</p></body></html>";
		public static final String lblTicketPaymentNumber = "#Ticket";
		public static final String lblTicketPaymentCard = "Numero carta";
		public static final String lblPayBtn = "Paga";
		public static final String lbl_PAG_TICK_SrvText = "Compila il modulo inserendo il numero ticket e il numero di carta";
		public static final String msgTicketPaymentSuccess = "Pagamento completato con successo";
		public static final String errInvalidCardNumber = "Il numero di carta deve contenere almeno 15 cifre";
		public static final String lblSchoolFee = "Quota (senza decimali)";
		public static final String lbl_PAG_RET_SrvTitle = "Pagamento Retta";
		public static final String[] monthValues = new String[]{"Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"};
		public static final String lbl_PAG_RET_SrvText = "Compila il modulo inserendo il mese di competenza e la quota della retta da pagare";
		public static final String lblTicketPaymentUser = "Codice Fiscale";
		public static final String lbl_PAG_TICK_SrvTitle = "Pagamento Ticket Ospedaliero";
		public static final String lbl_PAG_MEN_SrvTitle = "Pagamento Mensa Scolastica";
		public static final String lbl_PAG_MEN_SrvText = "Compila il modulo inserendo il mese di competenza e la quota relativa al servizio mensa da pagare";
		public static final String lblMonth = "Mese competenza";
		public static final String lbl_ISCRIZ_SrvTitle = "Iscrizione";
		public static final String lbl_ISCRIZ_SrvText = "<html><head><style>p { word-wrap: normal;}</style></head><body style=\"font-size: 16px;\"><p align=\"justify\" style=\"word-break:normal;white-space:normal\">Il/la sottoscritto/a <b>!first_name !surname</b>, nato/a a <b>!birth_town</b> (<b>!birth_province</b>) il <b>!birthdate</b>,<br/>CF <b>!tax_id_code</b> residente in via <b>!address, !town (!province), !zip_code</b></p><p align=\"center\"><b>RICHIEDE</b></p><p>l'iscrizione del/la proprio/a figlio/a &first_name &surname, nato/a a &birth_town, &birth_province il &birthdate,<br> CF &tax_id_code per l'anno scolastico 2024/2025</p></body></html>";
		public static final String errUserInvalid = "Impossibile trovare l'utente richiesto";
		public static final String lblServiceEditUser = "Modifica utente";
		public static final String lbluserCreationSearchUserBtn = "Cerca Utente";
		public static final String msgUserEditSuccess = "Utente modificato con successo";
		public static final String userEditConfirmMsg = "Per favore controlla i dati. Confermi di voler procedere alla modifica dell'utente?";
		public static final String userEditConfirmTitle = "Modifica utente";
		public static final String lbluserCreationSearchUserPlaceholder = "Scrivi l'utente da ricercare e premi invio";
        public static final String lblAdminSupportButtonBtnSide = "Gestione richieste";
		public static final String lblAdminSupport = "Gestione richieste";
	}
}
